using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GK3Reborn.Content;
using Xunit;

namespace GK3Reborn.Tests.Content;

/// <summary>
/// Tests for the scene dressing, which is the town of Couiza.
/// </summary>
/// <remarks>
/// <para>
/// The table is generated by <c>tools/blender/build_couiza.py</c> and every property here
/// is one the generator is supposed to guarantee. They are checked again on this side
/// because the generator needs Blender and the game does not: a table regenerated on a
/// machine with a different donor set, or hand-edited despite the notice at the top of it,
/// reaches the player either way.
/// </para>
/// <para>
/// The failure these are all really about is a silent one. A dressing line that does not
/// apply, or that names a model twice, does not crash and does not warn — it shows as a
/// building that is not in the room, which nobody notices in a room whose whole problem is
/// that it is too empty.
/// </para>
/// </remarks>
public sealed class SceneDressingTests
{
    /// <summary>TR1's own file, cut down to the sections the dressing touches.</summary>
    private const string Tr1 =
        "[GENERAL]\r\nfloor=tr1_floor\r\ncameraBounds=tr1_cambnds\r\n\r\n"
        + "[ACTORS]\r\nmodel=gab,noun=GABRIEL,pos=FR_MAP,ego\r\n\r\n"
        + "[MODELS]\r\n"
        + "model=tr1_fftree1,  type=prop\r\n"
        + "model=tudorbasic01, noun=OTR_BUILDINGS,   type=scene\r\n"
        + "model=tr1_station,  noun=STATION,        type=scene\r\n"
        + "\r\n[INSPECT_CAMERAS]\r\n"
        + "model=tr1_station, angle={-95.38, 2.00}, pos={960.23, 96.44, 90.25}\r\n";

    private static CutContent Dressing() => CutContent.Open(CutContentTier.None, dressing: true);

    private static string Apply(CutContent table) =>
        Encoding.Latin1.GetString(
            table.Apply("TR1.SIF", Encoding.Latin1.GetBytes(Tr1)));

    /// <summary>The model lines the dressing adds, as (name, whole line).</summary>
    private static List<(string Model, string Line)> Added()
    {
        var added = new List<(string, string)>();

        foreach (string line in Apply(Dressing()).Split('\n'))
        {
            string body = line.Trim();

            if (!body.StartsWith("model=RBN_CZ_", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            string name = body["model=".Length..].Split(',')[0].Trim();
            added.Add((name, body));
        }

        return added;
    }

    [Fact]
    public void NothingIsDressedWhenTheGeometryIsNotInstalled()
    {
        // The gate is the geometry itself, and this is the case that matters: a player
        // with no content packs must get the room exactly as it shipped, with no
        // diagnostics about forty models that are not there.
        CutContent table = CutContent.Open(CutContentTier.None, dressing: false);

        Assert.True(table.IsEmpty);
        Assert.Equal(Tr1, Apply(table));
    }

    [Fact]
    public void TheDressingIsNotPartOfTheRestorations()
    {
        // Two tables and two switches. Everything in CutContent.txt is the developers' own
        // data switched back on; none of this is, and the day the two are merged is the day
        // "content the game shipped with" starts meaning "content we thought it should
        // have had".
        CutContent restorations = CutContent.Open(CutContentTier.Reconstructed);

        Assert.DoesNotContain(
            "RBN_CZ_",
            Encoding.Latin1.GetString(restorations.Apply("TR1.SIF", Encoding.Latin1.GetBytes(Tr1))),
            StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void EveryLineOfTheTableCanBeRead()
    {
        // A line the parser cannot read is a building that never appears and says nothing
        // about it, which is the same silence the room already suffers from.
        Assert.Equal(0, Dressing().Unreadable);
    }

    [Fact]
    public void EveryEditAppliesToTheRoomItNames()
    {
        CutContent table = Dressing();

        Apply(table);

        Assert.Equal(0, table.Failed);
        Assert.Equal(table.EditCount, table.Applied);
    }

    [Fact]
    public void TheDressingOnlyTouchesTr1()
    {
        // One room so far. If that changes the change should be deliberate, because a
        // dressing table that quietly reaches a second room is a room somebody has to
        // discover has been changed.
        Assert.Equal(["TR1.SIF"], Dressing().Names);
    }

    [Fact]
    public void NoTwoPlacementsNameOneModel()
    {
        // SceneDefinition.MergeModels keys a room's models by name, and TR1 has both a room
        // file and timeblock files, so the merge runs. Two lines naming one model are one
        // building, and the other one is simply not in the room.
        List<string> names = [.. Added().Select(a => a.Model)];

        Assert.Equal(names.Count, names.Distinct(StringComparer.OrdinalIgnoreCase).Count());
    }

    [Fact]
    public void EveryBuildingIsAPropAndAnswersToTheRoomsOwnNoun()
    {
        // type=scene means "an object already inside the BSP" and loads no file at all, so
        // a facade declared that way is counted and never drawn. OTR_BUILDINGS is TR1's
        // own noun with its own recorded LOOK line, which is why the town needs no
        // dialogue.
        foreach ((string model, string line) in Added().Where(a => IsBuilding(a.Model)))
        {
            Assert.Contains("type=prop", line, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("noun=OTR_BUILDINGS", line, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("pos={", line, StringComparison.Ordinal);
        }
    }

    /// <summary>Whether a model is a building rather than a tree card or a lane.</summary>
    private static bool IsBuilding(string model) =>
        !model.Contains("TREE", StringComparison.OrdinalIgnoreCase) &&
        !IsSurface(model);

    /// <summary>Whether a model is a road or an apron rather than something built.</summary>
    private static bool IsSurface(string model) =>
        model.Contains("ROAD", StringComparison.OrdinalIgnoreCase) ||
        model.Contains("APRON", StringComparison.OrdinalIgnoreCase);

    [Fact]
    public void EveryLaneIsLaidWhereItWasAuthored()
    {
        // A lane follows the ground, so its vertices are the room's own coordinates and a
        // pos would move it off the floor it was draped over.
        //
        // And it is a decal, which is what keeps it out of the picker. A road declared
        // `prop` is the nearest thing the ray meets, `FloorTarget` wants the floor by
        // name, and the player cannot walk on ground he can plainly see.
        List<(string Model, string Line)> lanes = [.. Added().Where(a => IsSurface(a.Model))];

        Assert.NotEmpty(lanes);

        foreach ((string model, string line) in lanes)
        {
            Assert.DoesNotContain("pos=", line, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("type=decal", line, StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public void EveryTreeIsACardStandingWhereItWasAuthored()
    {
        // A grown tree carries its own transform and pos is never consulted once the tree
        // pass has claimed a model, so a tree card with a pos would be a tree standing
        // somewhere the layout did not put it — and there would be nothing on screen to
        // say which of the two places was meant.
        List<(string Model, string Line)> trees =
            [.. Added().Where(a => a.Model.Contains("TREE", StringComparison.OrdinalIgnoreCase))];

        Assert.NotEmpty(trees);

        foreach ((string model, string line) in trees)
        {
            Assert.DoesNotContain("pos=", line, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("type=prop", line, StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public void NothingThatShippedIsMovedOrRenamed()
    {
        // The whole claim of this feature. Every line TR1 already had has to survive the
        // edit unchanged; the dressing may only add.
        string[] before = Tr1.Split('\n');
        string[] after = Apply(Dressing()).Split('\n');

        foreach (string line in before)
        {
            Assert.Contains(line, after);
        }

        Assert.True(after.Length > before.Length);
    }

    [Fact]
    public void ApplyingTwiceChangesNothingTheSecondTime()
    {
        // `append` is idempotent, and it has to be: the table is applied to the bytes on
        // their way out of the archive, and the archive is read again every time the
        // player walks into the room.
        CutContent table = Dressing();

        string once = Apply(table);
        string twice = Encoding.Latin1.GetString(
            table.Apply("TR1.SIF", Encoding.Latin1.GetBytes(once)));

        Assert.Equal(once, twice);
    }
}
